version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true # Ensures fast hot-reloads within containers