# from fastapi import APIRouter, Depends, HTTPException, status, BackgroundTasks
# from sqlalchemy.orm import Session
# from app.core.database import get_db
# from app.schemas.email import EmailPayload
# from app.models.schema import Email, Thread, Contact, Action
# from app.services.heuristics import run_heuristic_pre_filter
# from app.services.intelligence import analyze_email_intelligence
# from app.agent.workflow import run_agent_loop
# from app.services.scraper import fetch_web_intelligence
# import asyncio

# router = APIRouter()

# @router.post("/ingest", status_code=status.HTTP_202_ACCEPTED)
# def ingest_email(payload: EmailPayload, background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
#     # 1. Idempotency Guard: Stop duplicate emails
#     existing_email = db.query(Email).filter(Email.message_id == payload.message_id).first()
#     if existing_email:
#         return {"status": "ignored", "detail": "Duplicate message_id captured."}

#     # 2. Contact Sync: Create user if they don't exist
#     contact = db.query(Contact).filter(Contact.email == payload.sender).first()
#     if not contact:
#         contact = Contact(email=payload.sender)
#         db.add(contact)
#         db.flush()

#     # 3. Thread Management: Group emails by conversation
#     thread = db.query(Thread).filter(Thread.thread_id == payload.thread_id).first()
#     if not thread:
#         thread = Thread(
#             thread_id=payload.thread_id,
#             subject=payload.subject if payload.subject else "No Subject",
#             sender_email=payload.sender
#         )
#         db.add(thread)
#         db.flush()

#     # 4. Intelligence Execution: THE BRAIN
#     # First, run the fast regex scanner
#     # 4. Intelligence Execution: THE BRAIN
#     # First, run the fast regex scanner (Passing sender now!)
#     ai_profile = run_heuristic_pre_filter(payload.body, payload.subject, payload.sender)
    
#     # If regex found nothing dangerous, ask Gemini Flash to classify it
#     if not ai_profile:
#         ai_profile = analyze_email_intelligence(payload.body, payload.subject, db)

#     # --- BUSINESS RULE 1: Low Confidence Override (Layer 2 Requirement) ---
#     if ai_profile.get("confidence", 1.0) < 0.70:
#         ai_profile["requires_human"] = True
#         ai_profile["reasoning"] = "System Confidence below 0.70. Forcing human review."

#     # --- BUSINESS RULE 2: Sentiment Deterioration Alert (Layer 3 Requirement) ---
#     # Check if the last 2 emails from this sender were negative (< -0.2)
#     # If this current one is also negative, we escalate immediately.
#     is_currently_negative = ai_profile.get("sentiment_score", 0) < -0.2
    
#     if is_currently_negative:
#         past_emails = db.query(Email)\
#             .filter(Email.sender == payload.sender)\
#             .order_by(Email.timestamp.desc())\
#             .limit(2).all()
            
#         # If we have 2 past emails and BOTH are negative
#         if len(past_emails) == 2 and all(e.sentiment_score and e.sentiment_score < -0.2 for e in past_emails):
#             ai_profile["requires_human"] = True
#             ai_profile["urgency"] = "Critical"
#             ai_profile["category"] = "Escalation"
#             ai_profile["reasoning"] = "3 consecutive negative emails detected. Immediate churn risk alert."
#     # ------------------------------------------------------------

#     # 5. Save everything to Supabase
#     new_email = Email(
#         thread_id=thread.thread_id,
#         message_id=payload.message_id,
#         sender=payload.sender,
#         subject=payload.subject,
#         body=payload.body,
#         timestamp=payload.timestamp,
        
#         # Grab the fields generated by the AI
#         sentiment_score=ai_profile.get("sentiment_score"),
#         category=ai_profile.get("category"),
#         urgency=ai_profile.get("urgency"),
#         requires_human=ai_profile.get("requires_human", False),
#         confidence=ai_profile.get("confidence"),
#         raw_entities={"reasoning": ai_profile.get("reasoning")},
        
#         # If human is needed, escalate it immediately
#         status="Escalated" if ai_profile.get("requires_human") else "Processing"
#     )
    
#     # Update the parent thread status if things are bad
#     if ai_profile.get("urgency") in ["High", "Critical"]:
#         thread.status = "Escalated"

#     db.add(new_email)
    
#     try:
#         db.commit()
#         db.refresh(new_email) # <-- We need this to get the new email ID from the database
        
#         # --- NEW AGENT EXECUTION BLOCK ---
#         # 1. Trigger the AI Agent to process the email body
#         agent_result = run_agent_loop(
#             email_body=new_email.body, 
#             thread_id=new_email.thread_id, 
#             db=db
#         )
        
#         # 2. Save the Agent's Chain-of-Thought log to the database
#         action_record = Action(
#             email_id=new_email.id,
#             action_type=agent_result.get("final_action", "unknown"),
#             agent_reasoning_log=agent_result.get("reasoning_log", [])
#         )
#         db.add(action_record)
#         db.commit()
#         # ---------------------------------

#     except Exception as e:
#         db.rollback()
#         raise HTTPException(status_code=500, detail=str(e))

#     # Respond to the client with the AI's classification
#     return {
#         "status": "success", 
#         "message_id": payload.message_id,
#         "classification": {
#             "category": new_email.category,
#             "urgency": new_email.urgency,
#             "requires_human": new_email.requires_human
#         }
#     }

from fastapi import APIRouter, Depends, HTTPException, status, BackgroundTasks
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.schemas.email import EmailPayload
from app.models.schema import Email, Thread, Contact, Action
from app.services.heuristics import run_heuristic_pre_filter
from app.services.intelligence import analyze_email_intelligence
from app.agent.workflow import run_agent_loop
from app.services.scraper import fetch_web_intelligence
import asyncio

router = APIRouter()

@router.post("/ingest", status_code=status.HTTP_202_ACCEPTED)
def ingest_email(payload: EmailPayload, background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    # 1. Idempotency Guard: Stop duplicate emails
    existing_email = db.query(Email).filter(Email.message_id == payload.message_id).first()
    if existing_email:
        return {"status": "ignored", "detail": "Duplicate message_id captured."}

    # 2. Contact Sync: Create user if they don't exist
    contact = db.query(Contact).filter(Contact.email == payload.sender).first()
    if not contact:
        contact = Contact(email=payload.sender)
        db.add(contact)
        db.flush()

    # 3. Thread Management: Group emails by conversation
    thread = db.query(Thread).filter(Thread.thread_id == payload.thread_id).first()
    if not thread:
        thread = Thread(
            thread_id=payload.thread_id,
            subject=payload.subject if payload.subject else "No Subject",
            sender_email=payload.sender
        )
        db.add(thread)
        db.flush()

    # 4. Intelligence Execution: THE BRAIN
    # First, run the fast regex scanner (Passing sender now!)
    ai_profile = run_heuristic_pre_filter(payload.body, payload.subject, payload.sender)
    
    # If regex found nothing dangerous, ask Gemini Flash to classify it
    if not ai_profile:
        ai_profile = analyze_email_intelligence(payload.body, payload.subject, db)

    # --- BUSINESS RULE 1: Low Confidence Override (Layer 2 Requirement) ---
    if ai_profile.get("confidence", 1.0) < 0.70:
        ai_profile["requires_human"] = True
        ai_profile["reasoning"] = "System Confidence below 0.70. Forcing human review."

    # --- BUSINESS RULE 2: Sentiment Deterioration Alert (Layer 3 Requirement) ---
    is_currently_negative = ai_profile.get("sentiment_score", 0) < -0.2
    
    if is_currently_negative:
        past_emails = db.query(Email)\
            .filter(Email.sender == payload.sender)\
            .order_by(Email.timestamp.desc())\
            .limit(2).all()
            
        if len(past_emails) == 2 and all(e.sentiment_score and e.sentiment_score < -0.2 for e in past_emails):
            ai_profile["requires_human"] = True
            ai_profile["urgency"] = "Critical"
            ai_profile["category"] = "Escalation"
            ai_profile["reasoning"] = "3 consecutive negative emails detected. Immediate churn risk alert."
    # ------------------------------------------------------------

    # --- COMPONENT 5: WEB INTELLIGENCE TRIGGERS ---
    body_lower = payload.body.lower()
    trigger_keywords = ['review', 'trustpilot', 'g2', 'twitter', 'post publicly']

    needs_scraping = False
    if any(word in body_lower for word in trigger_keywords):
        needs_scraping = True
    elif ai_profile.get("sentiment_score", 0) < -0.6:
        needs_scraping = True
    elif ai_profile.get("category") == "Complaint" and ai_profile.get("urgency") in ["High", "Critical"]:
        needs_scraping = True

    if needs_scraping:
        # Fire and forget! Doesn't block the API response.
        background_tasks.add_task(fetch_web_intelligence, "SenAI")
    # ----------------------------------------------

    # 5. Save everything to Supabase
    new_email = Email(
        thread_id=thread.thread_id,
        message_id=payload.message_id,
        sender=payload.sender,
        subject=payload.subject,
        body=payload.body,
        timestamp=payload.timestamp,
        
        sentiment_score=ai_profile.get("sentiment_score"),
        category=ai_profile.get("category"),
        urgency=ai_profile.get("urgency"),
        requires_human=ai_profile.get("requires_human", False),
        confidence=ai_profile.get("confidence"),
        raw_entities={"reasoning": ai_profile.get("reasoning")},
        
        status="Escalated" if ai_profile.get("requires_human") else "Processing"
    )
    
    if ai_profile.get("urgency") in ["High", "Critical"]:
        thread.status = "Escalated"

    db.add(new_email)
    
    try:
        db.commit()
        db.refresh(new_email) 
        
        # --- AGENT EXECUTION BLOCK ---
        # DISQUALIFIER GUARD: NEVER run the agent on Spam (Prevents accidental auto-replies)
        if new_email.category == "Spam":
            action_record = Action(
                email_id=new_email.id,
                action_type="ignored",
                agent_reasoning_log=[{"step": 0, "thought": "Email classified as Spam. Ignored to prevent auto-reply loop.", "action": "none"}]
            )
            db.add(action_record)
            db.commit()
        else:
            # Trigger the AI Agent for legitimate emails
            agent_result = run_agent_loop(
                email_body=new_email.body, 
                thread_id=new_email.thread_id, 
                db=db,
                sender_email=new_email.sender,
                urgency=new_email.urgency
            )
            
            # Save the Agent's Chain-of-Thought log
            action_record = Action(
                email_id=new_email.id,
                action_type=agent_result.get("final_action", "unknown"),
                agent_reasoning_log=agent_result.get("reasoning_log", [])
            )
            db.add(action_record)
            db.commit()
        # ---------------------------------

    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))

    return {
        "status": "success", 
        "message_id": payload.message_id,
        "classification": {
            "category": new_email.category,
            "urgency": new_email.urgency,
            "requires_human": new_email.requires_human
        }
    }