from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.schemas.email import EmailPayload
from app.models.schema import Email, Thread, Contact
from app.services.heuristics import run_heuristic_pre_filter
from app.services.intelligence import analyze_email_intelligence

router = APIRouter()

@router.post("/ingest", status_code=status.HTTP_202_ACCEPTED)
def ingest_email(payload: EmailPayload, db: Session = Depends(get_db)):
    # 1. Idempotency Guard: Stop duplicate emails
    existing_email = db.query(Email).filter(Email.message_id == payload.message_id).first()
    if existing_email:
        return {"status": "ignored", "detail": "Duplicate message_id captured."}

    # 2. Contact Sync: Create user if they don't exist
    contact = db.query(Contact).filter(Contact.email == payload.sender).first()
    if not contact:
        contact = Contact(email=payload.sender)
        db.add(contact)
        db.flush()

    # 3. Thread Management: Group emails by conversation
    thread = db.query(Thread).filter(Thread.thread_id == payload.thread_id).first()
    if not thread:
        thread = Thread(
            thread_id=payload.thread_id,
            subject=payload.subject if payload.subject else "No Subject",
            sender_email=payload.sender
        )
        db.add(thread)
        db.flush()

    # 4. Intelligence Execution: THE BRAIN
    # First, run the fast regex scanner
    ai_profile = run_heuristic_pre_filter(payload.body, payload.subject)
    
    # If regex found nothing dangerous, ask Gemini Flash to classify it
    if not ai_profile:
        ai_profile = analyze_email_intelligence(payload.body, payload.subject, db)

    # 5. Save everything to Supabase
    new_email = Email(
        thread_id=thread.thread_id,
        message_id=payload.message_id,
        sender=payload.sender,
        subject=payload.subject,
        body=payload.body,
        timestamp=payload.timestamp,
        
        # Grab the fields generated by the AI
        sentiment_score=ai_profile.get("sentiment_score"),
        category=ai_profile.get("category"),
        urgency=ai_profile.get("urgency"),
        requires_human=ai_profile.get("requires_human", False),
        confidence=ai_profile.get("confidence"),
        raw_entities={"reasoning": ai_profile.get("reasoning")},
        
        # If human is needed, escalate it immediately
        status="Escalated" if ai_profile.get("requires_human") else "Processing"
    )
    
    # Update the parent thread status if things are bad
    if ai_profile.get("urgency") in ["High", "Critical"]:
        thread.status = "Escalated"

    db.add(new_email)
    
    try:
        db.commit()
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))

    # Respond to the client with the AI's classification
    return {
        "status": "success", 
        "message_id": payload.message_id,
        "classification": {
            "category": new_email.category,
            "urgency": new_email.urgency,
            "requires_human": new_email.requires_human
        }
    }